name: audio_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - aom=3.9.1=hf036a51_0
  - audioread=3.0.1=py311h6eed73b_3
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - brotli-python=1.2.0=py311h7e844b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.16.0=h08824b9_6
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h9d13916_4
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=h0dc2134_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - ffmpeg=4.3.2=h4dad6da_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.61.1=py311he13f9b5_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.16=h8616949_0
  - gettext=0.25.1=he52a196_1
  - gettext-tools=0.25.1=h3184127_1
  - gmp=6.3.0=hf036a51_2
  - gnutls=3.6.13=h756fd2b_1
  - graphite2=1.3.14=h21dd04a_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=h060d35a_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hf5e326d_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - kiwisolver=1.4.9=py311h591569d_2
  - lame=3.100=hb7f2c08_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=hcca01a6_1
  - libasprintf=0.25.1=h3184127_1
  - libasprintf-devel=0.25.1=h3184127_1
  - libavif=1.3.0=hef75fda_3
  - libavif16=1.3.0=hef75fda_3
  - libblas=3.11.0=5_he492b99_openblas
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcblas=3.11.0=5_h9b27e0a_openblas
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h00291cd_0
  - libffi=3.4.4=hecd8cb5_1
  - libflac=1.5.0=hbafe72d_1
  - libgcc=15.2.0=h08519bb_17
  - libgettextpo=0.25.1=h3184127_1
  - libgettextpo-devel=0.25.1=h3184127_1
  - libgfortran=15.2.0=h7e5c614_17
  - libgfortran5=15.2.0=hd16e46c_17
  - libglib=2.84.2=heb90364_0
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libintl-devel=0.25.1=h3184127_1
  - liblapack=3.11.0=5_h859234e_openblas
  - libogg=1.3.5=he3325bb_1
  - libopenblas=0.3.30=openmp_h6006d49_4
  - libopus=1.6.1=hc6ced15_0
  - libpng=1.6.39=h6c40b1e_0
  - librosa=0.11.0=pyhd8ed1ab_0
  - libsndfile=1.2.2=h4b11300_2
  - libtiff=4.7.0=h2dfa3ea_0
  - libvorbis=1.3.7=ha059160_2
  - libwebp-base=1.6.0=hb807250_0
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=ha54dae1_1
  - llvmlite=0.44.0=py311hfa5e528_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - matplotlib-base=3.10.1=py311h19a4563_0
  - mpg123=1.32.9=h78e78a4_0
  - msgpack-python=1.1.2=py311haec20ae_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h923df54_0
  - nettle=3.6=hedd7734_0
  - numba=0.61.0=py311h5322ac9_1
  - openh264=2.1.1=hfd3ada9_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.6.1=hb6871ef_1
  - packaging=26.0=pyhcf101f3_0
  - pcre2=10.42=h9b97e30_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=ha059160_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pooch=1.9.0=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - qhull=2020.2=h3c5361c_5
  - rav1e=0.7.1=h371c88c_3
  - readline=8.3=h49f2429_0
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.8.0=np2py311heeb2b4f_1
  - scipy=1.17.0=py311h553d447_1
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - soxr=0.1.3=hbf74d83_3
  - soxr-python=1.0.0=py311h11ccb26_1
  - sqlite=3.50.2=hc8b0dd6_1
  - standard-aifc=3.13.0=py311h6eed73b_3
  - standard-sunau=3.13.0=py311h6eed73b_3
  - svt-av1=4.0.0=h991f03e_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h3a5a201_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - unicodedata2=17.0.0=py311hf197a57_1
  - wheel=0.45.1=py311hecd8cb5_0
  - x264=1!161.3030=h0d85af4_1
  - xz=5.6.4=h46256e1_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.2.13=h4b97444_1
  - zstandard=0.23.0=py311h13e5629_3
  - zstd=1.5.6=h138b38a_0
  - pip:
      - anyio==4.12.1
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - cffi==2.0.0
      - comm==0.2.3
      - debugpy==1.8.20
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numpy==2.4.2
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==3.0
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - send2trash==2.1.0
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
prefix: /opt/anaconda3/envs/audio_env
